name: Generate Custom Image
on: [push]
env:
  image_name: my_rpi_custom_image.img

jobs:
  generate_custom_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Image Fetcher
        run: python3 rpi_image_customizer/src/image_fetcher.py ${{ env.image_name }}

      - name: Gather User Data
        run: python3 rpi_image_customizer/src/gather_user_data.py

      - name: Render template
        run: python3 rpi_image_customizer/src/template_render.py
        env:
          HOSTNAME: ${{ secrets[format('{0}', env.host_name)] }}
          NAMEUSER: ${{ secrets[format('{0}', env.user_name)] }}
          NAMEUSERPASSWORD: ${{ secrets[format('{0}', env.user_name_password)] }}
          WIFISSID: ${{ secrets[format('{0}', env.wifi_ssid)] }}
          WIFIPASSWORD: ${{ secrets[format('{0}', env.wifi_password)] }}
          SSHPUBLICKEY: ${{ secrets[format('{0}', env.ssh_public_key)] }}

      - name: Run script
        run: sudo sh ./rpi_image_customizer/src/customize_image.sh ${{ env.image_name }}

      - name: check file
        run: cat first_run.sh

      - name: Upload data to artifactory
        uses: actions/upload-artifact@v4
        with:
          name: Rasp_custom_image
          path: ${{ env.image_name }}