name: Generate Custom Image
on: [push]

env:
  image_name: my_image.img

jobs:
  generate_custom_image:
    runs-on: ubuntu-22.04
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: Download a file
        run: curl https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2023-02-22/2023-02-21-raspios-buster-armhf-lite.img.xz -o ${{ env.image_name }}
      
      - name: Upload data to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: Rasp_custom_image
          path: ${{ env.image_name }}